Disabled using M1 GPU
It turns out that torch.multinormal is currently not implemented for the MPS device. At this point, making the code work is the first priority. So let's use CPU and make it work, and later find a way to use MPS.

Error log below.

	Traceback (most recent call last):
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/scripts/run_hw2.py", line 123, in <module>
	    main()
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/scripts/run_hw2.py", line 119, in main
	    trainer.run_training_loop()
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/scripts/run_hw2.py", line 48, in run_training_loop
	    self.rl_trainer.run_training_loop(
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/infrastructure/rl_trainer.py", line 138, in run_training_loop
	    training_returns = self.collect_training_trajectories(itr,
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/infrastructure/rl_trainer.py", line 191, in collect_training_trajectories
	    paths, envsteps_this_batch = utils.sample_trajectories(
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/infrastructure/utils.py", line 105, in sample_trajectories
	    path = sample_trajectory(env, policy, max_path_length, render, render_mode)
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/infrastructure/utils.py", line 75, in sample_trajectory
	    ac = policy.get_action(ob)
	  File "/Users/lds3rd/repos/UCBerkeleyCS285/homework_fall2022/hw2/cs285/policies/MLP_policy.py", line 96, in get_action
	    action_sample = action_distribution.sample()
	  File "/opt/homebrew/Caskroom/miniforge/base/envs/cs285/lib/python3.9/site-packages/torch/distributions/categorical.py", line 116, in sample
	    samples_2d = torch.multinomial(probs_2d, sample_shape.numel(), True).T
	NotImplementedError: The operator 'aten::multinomial' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.